<script lang="ts">
import { defineComponent, h } from 'vue';
import { VueLatex } from 'vatex';

export default defineComponent({
  components: {
    VueLatex,
  },
  setup() {
    // Table data
    const tableData = [
      {
        scenarioType: 'Concert Event',
        lightingSource: 'Human Design',
        s_exp: 2.58,
        s_non: 4.31,
        egss: 3.09,
        rowspan: 2,
      },
      {
        scenarioType: 'Concert Event',
        lightingSource: 'AuraLuxMuse',
        s_exp: 3.29,
        s_non: 3.19,
        egss: 3.26,
        rowspan: 0,
      },
      {
        scenarioType: 'Drama Show',
        lightingSource: 'Human Design',
        s_exp: 3.08,
        s_non: 4.03,
        egss: 3.36,
        rowspan: 2,
      },
      {
        scenarioType: 'Drama Show',
        lightingSource: 'AuraLuxMuse',
        s_exp: 2.45,
        s_non: 3.23,
        egss: 2.68,
        rowspan: 0,
      },
      {
        scenarioType: 'Entertainment Act',
        lightingSource: 'Human Design',
        s_exp: 2.46,
        s_non: 3.31,
        egss: 2.71,
        rowspan: 2,
      },
      {
        scenarioType: 'Entertainment Act',
        lightingSource: 'AuraLuxMuse',
        s_exp: 2.76,
        s_non: 3.99,
        egss: 3.12,
        rowspan: 0,
      },
      {
        scenarioType: 'Average',
        lightingSource: 'Human Design',
        s_exp: 2.71,
        s_non: 3.88,
        egss: 3.05,
        rowspan: 2,
      },
      {
        scenarioType: 'Average',
        lightingSource: 'AuraLuxMuse',
        s_exp: 2.83,
        s_non: 3.47,
        egss: 3.02,
        rowspan: 0,
      },
    ];

    // Span method for rowspan in Scenario Type column
    const spanMethod = ({ row, column, rowIndex, columnIndex }) => {
      if (columnIndex === 0) { // Scenario Type column
        return { rowspan: row.rowspan, colspan: 1 };
      }
      return { rowspan: 1, colspan: 1 };
    };

    return { tableData, spanMethod };
  },
});
</script>

<template>
  <div>
    <el-divider />

    <el-row justify="center">
      <h1 class="section-title">Quantitative Results</h1>
    </el-row>

    <el-row justify="center">
      <el-col :xs="24" :sm="20" :md="16" :lg="12" :xl="12">
        <el-card class="card">
          <div class="content-container">
            <p class="caption">
              The following table presents a quantitative comparison of stage lighting quality between human-designed shows and those generated by AuraLuxMuse across three scenarios. A human evaluation involving 40 professional lighting designers and 40 non-experts ensured rigorous results. Professionals rated lighting based on five dimensions, while general audiences provided perceptual feedback, both on a 1–5 scale. The Expert-Guided Subjective Score, defined as <VueLatex expression="\text{EGSS} = \lambda \cdot S_{\text{exp}} + (1 - \lambda) \cdot S_{\text{non}}, \lambda \in [0, 1]" />, with <VueLatex expression="\lambda = 0.7" />, integrates expert ratings <VueLatex expression="S_{\text{exp}}" /> and non-expert ratings <VueLatex expression="S_{\text{non}}" /> to balance professional expertise with audience perception. AuraLuxMuse demonstrates comparable quantitative performance to human designs, reflecting its ability to produce high-quality, perceptually effective lighting.
            </p>
            <el-table
              :data="tableData"
              style="width: 100%; max-width: 600px; margin: 20px auto;"
              row-class-name="custom-row"
              :span-method="spanMethod"
            >
              <el-table-column
                prop="scenarioType"
                label="Scenario Type"
                min-width="150"
                align="center"
              />
              <el-table-column
                prop="lightingSource"
                label="Lighting Source"
                min-width="150"
                align="center"
              />
              <el-table-column
                prop="s_exp"
                min-width="100"
                align="center"
              >
                <template #header>
                  <VueLatex expression="S_{\text{exp}}" />
                </template>
              </el-table-column>
              <el-table-column
                prop="s_non"
                min-width="100"
                align="center"
              >
                <template #header>
                  <VueLatex expression="S_{\text{non}}" />
                </template>
              </el-table-column>
              <el-table-column
                prop="egss"
                label="EGSS"
                min-width="100"
                align="center"
              />
            </el-table>
          </div>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<style scoped>
/* Center the content container */
.content-container {
  display: flex;
  flex-direction: column;
  align-items: center;
}

/* Style the card */
.card {
  margin-top: 20px;
}

/* Style the caption */
.caption {
  text-indent: 32px;
  font-family: "Helvetica Neue", Arial, sans-serif;
  font-size: 16px;
  color: #000;
  margin: 0 0 20px 0;
  line-height: 1.6;
}

/* Style the table */
.el-table {
  width: 100%;
  max-width: 600px;
  margin: 20px auto;
  font-family: "Helvetica Neue", Arial, sans-serif;
  font-size: 14px;
  line-height: 1.5;
  border-collapse: collapse;
}

/* Style table headers */
:deep(.el-table th),
:deep(.el-table__header th) {
  background-color: #ddd;
  font-weight: 600;
  text-align: center;
  padding: 12px;
  border: 1px solid #ddd;
  min-width: 100px;
  color: #000000 !important; /* 强制所有表头文字为黑色 */
}

/* Ensure LaTeX-rendered headers are also black */
:deep(.el-table th .katex) {
  color: #000000 !important; /* 强制 LaTeX 文字为黑色 */
}

/* Style table cells */
.el-table td {
  text-align: center;
  padding: 12px;
  border: 1px solid #ddd;
  font-weight: 400;
  min-width: 100px;
  font-style: normal;
}


/* Ensure bold for Scenario Type */
:deep(.el-table__row td:first-child) {
  font-weight: 600;
}
</style>